# NumPy Basics

1. Review를 위한 단계
- 방식 : chapter04 장을 보면서 이해하고 주석 달기
- 제출 방식 : 강사가 제시한 폴더에 파일명 수정해서 제출하
- 파일명 : **step05_bookReview임동원.ipynb**

In [30]:
import numpy as np
import pandas as pd

## The NumPy ndarray: A Multidimensional Array Object

In [18]:
#randn이라는 함수는 (a,b)에 숫자를 입력하면, axb사이즈의 행렬을 자동으로 만드는 것으로 추정된다. 
#출력되는 원소값들은 각각 평균0, 분산1의 데이터가 임의로 출력된다.
data = np.random.randn(2, 3)
data

array([[ 1.49104786, -0.99780067,  0.90570906],
       [-0.04820493,  0.85520794, -0.34769676]])

In [19]:
data = np.random.randn(3, 4)
data

array([[ 0.96794594, -0.53207529, -0.27576025,  1.03477816],
       [-0.52431706,  1.23084749, -0.33343193, -0.68469487],
       [-1.84050898,  1.36978023, -1.00195896, -0.2918403 ]])

In [22]:
print(data * 10)
print(data + data)
#data는 array형태이기 때문에, array*10는 각 요소에 10을 곱한 값들이 출력되고, 
#array+array의 경우 같은 행 같은 열의 성분이 더해진 값들이 출력된다.

[[  9.67945935  -5.32075294  -2.75760247  10.34778157]
 [ -5.24317057  12.30847493  -3.3343193   -6.84694871]
 [-18.40508982  13.69780227 -10.01958958  -2.91840305]]
[[ 1.93589187 -1.06415059 -0.55152049  2.06955631]
 [-1.04863411  2.46169499 -0.66686386 -1.36938974]
 [-3.68101796  2.73956045 -2.00391792 -0.58368061]]


In [25]:
print(data.shape)# data는 3행4열의 행렬구조이다.
print(data.dtype)# data의 모든 요소는 평균0, 분산1의 임의의 데이터값들이므로 float값이다.

(3, 4)
float64


### Creating ndarrays

In [27]:
#리스트와  np.array는 비슷해 보이지만 차이가 있다. 예를들어, 리스트*2의 경우, 동일한 원소값들이 2번 반복되어 출력된다.
#하지만 array의 경우 array*2를 하면 각 요소가 2배가 된 array가 출력된다.
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [32]:
#다음 array는 2차원 배열로 흔히 수학에서 쓰이는 행렬과 같은 구조라고 볼 수 있으며, 
#판다스에서 가장 많이 쓰이는 자료형인 DataFrame형태로 변경 가능하다.
#문법은 pd.DataFrame(data2) 이다.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
#arr2는 2행 4열 행렬형태이며 2차원 배열이다
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [41]:
#array의 경우, array의 값이 하나라도 float이면 모든 값이 float으로 저장되고, 모두가 int인 경우에만 int로 저장된다.
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [42]:
#np.zeros는 괄호 안에 배열의 크기가 들어가게 된다.
#np.zeros(10)의경우 10개의 데이터가 0으로 채워진 1차원 배열이 나오고,
#np.zeros((3,6))의 경우 3x6행렬의 shape가 모두 0으로 채워진 배열이 출력된다.
print(np.zeros(10))
print(np.zeros((3, 6)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [45]:
#np.arange는 괄호 안에 숫자까지, 그 숫자를 제외하고 default값인 0부터 1씩 증가시키며 출력한다
print(np.arange(15))
#값을 2개를 주어 시작값을 조정할 수 있다.
print(np.arange(2,15))
#값을 3개를 주어 시작과 끝, 그리고 간격까지 조정 할 수 있다.
print(np.arange(2,15,2))
type(np.arange(2,15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


numpy.ndarray

### Data Types for ndarrays

In [47]:
#dtype함수를 이용하여 array의 원소값들의 type을 조정할 수 있다.
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [48]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [50]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)
#astype함수를 써서 array의 각 원소값들을 정수로 바꿀 수 있다. 이때 소숫점 아래는 모두 반올림이 아닌 버림이다.

array([ 3, -1, -2,  0, 12, 10])

In [51]:
#astype함수는 파라미터에 np.float64와 같이 명확한 값을 주어도 되고, 다른 특정 array의 데이터타입을 주어도 된다.
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [102]:
#array는 * 혹은 -연산시, 각 원소에 해당 값만큼을 곱해주거나 뺴준다
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
print(arr * arr)
print(arr - arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [103]:
#제곱 혹은 나누기도 마찬가지이다.
print(1 / arr)
print(arr ** 0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [54]:
#>, <,==와 같은 값들은, 배열간의 해당 성분의 값끼리 비교하여 true 혹은 false를 출력한다
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [55]:
#다음은 array slicing이다. 이때는 리스트와 같은 문법으로 원하는 값들을 출력하거나 수정할 수 있다.
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [56]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [57]:
#array의 일부를 슬라이싱하여 값을 수정하면, 기존의 array 값도 변경되니 이점은 주의해야한다.
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [58]:
#array_slice의 모든 요소를 64로 바꾸는 문법
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [105]:
#2차원 배열에서 []를 하나를 쓰면 가장 고차원에서 하나씩 원소를 찾아간다고 볼 수 있다.
#즉 다음 배열은 1차원 3개로 이루어진 2차원이므로 arr2d[2]를하면 1차원중 [2]에 해당하는 값이 출력된다.
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [106]:
#두개는 같은 문법이라고 보면된다.
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
#copy를 사용하여 값을 수정하면, 원본데이터가 변경되지 않는다.
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
#arr3d[1][0]과 같은 문법
arr3d[1, 0]

array([7, 8, 9])

In [65]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### Indexing with slices

In [66]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [67]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [69]:
arr2d[1, :2]

array([4, 5])

In [70]:
arr2d[:2, 2]

array([3, 6])

In [71]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [72]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [73]:
#7x4 size의 행렬에 평균0,분산1인 데이터들이 무작위로 채워지는 문법
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 0.41535237, -1.17441388,  0.88589589, -1.75116902],
       [-0.55336588, -0.10240626,  0.85248104, -0.53616813],
       [ 1.06164622, -0.55799081,  2.10359018,  0.91245112],
       [ 0.14082075, -0.49628492,  0.13580783, -0.61135203],
       [-0.68690054, -0.73415952, -1.40633714, -0.54795259],
       [-0.4018588 ,  1.6999153 ,  0.2675118 , -0.66629115],
       [-0.50392367,  2.0246638 , -0.09048792, -0.63196342]])

In [74]:
names == 'Bob'
#array의 값이 'Bob'이면 true, 아니면 false를 출력하는 문법

array([ True, False, False,  True, False, False, False])

In [75]:
# names=='Bob'은 0,3번째 요소만 true이다. 따라서 data중 0,3번째 1차원배열만 출력된다
data[names == 'Bob']

array([[ 0.41535237, -1.17441388,  0.88589589, -1.75116902],
       [ 0.14082075, -0.49628492,  0.13580783, -0.61135203]])

In [76]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

array([-1.75116902, -0.61135203])

In [77]:
#|의 경우 둘중 하나만 만족하면 True가 출력된다.
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[ 0.41535237, -1.17441388,  0.88589589, -1.75116902],
       [ 1.06164622, -0.55799081,  2.10359018,  0.91245112],
       [ 0.14082075, -0.49628492,  0.13580783, -0.61135203],
       [-0.68690054, -0.73415952, -1.40633714, -0.54795259]])

In [78]:
#data중 data값이 0보다 작은 원소들을 모두 0으로  바꿔주는 문법
data[data < 0] = 0
data

array([[0.41535237, 0.        , 0.88589589, 0.        ],
       [0.        , 0.        , 0.85248104, 0.        ],
       [1.06164622, 0.        , 2.10359018, 0.91245112],
       [0.14082075, 0.        , 0.13580783, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.6999153 , 0.2675118 , 0.        ],
       [0.        , 2.0246638 , 0.        , 0.        ]])

In [79]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.85248104, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.6999153 , 0.2675118 , 0.        ],
       [0.        , 2.0246638 , 0.        , 0.        ]])

### Transposing Arrays and Swapping Axes

In [80]:
#reshape는 아주 빈번히 쓰이는 문법으로 행렬의 shape를 바꿔준다. 이때 arange의 원소의 개수는 reshape의 파라미터값의 곱과 같아야한다.
# 즉 15=3x5
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

array([[ 5.27187654,  0.24618509, -3.16285503],
       [ 0.24618509,  9.0077469 ,  1.74480747],
       [-3.16285503,  1.74480747,  3.48569725]])

In [82]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [83]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [84]:
#sqrt는 모든 원소에 루트를 씌우는 문법이다
arr = np.arange(10)
arr
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
#np.maximum에 shape가같은 array 2개를 대입하면 각각의 원소 중 더 큰값을 선택하는 array가 출력된다
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

array([ 1.80320542,  0.94365204, -0.88626192,  0.53378466,  0.95604756,
        1.96128053,  0.45481441,  1.41482666])

In [111]:
#np.modf에 arrray를 대입하면 해당 array의 나머지, 몫이 출력된다
#np.random.randn은 대부분의 값이 0에 몰려있으므로 예제에서는 5를 곱해주어 최대한 1의자리값이 0이 아니게 출력했다.
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[-0.00128856  0.41292955  0.99675123  0.03532923 -0.0253157  -0.52581228
 -0.90092124]
[-9.  5.  1.  4. -5. -8. -0.]


In [113]:
#모든 원소의 루트값을 출력하는 문법
print(arr)
print(np.sqrt(arr))
print(np.sqrt(arr, arr))
print(arr)

[       nan 2.32657034 1.41306448 2.00881289        nan        nan
        nan]
[       nan 1.52530992 1.18872389 1.41732597        nan        nan
        nan]
[       nan 1.52530992 1.18872389 1.41732597        nan        nan
        nan]
[       nan 1.52530992 1.18872389 1.41732597        nan        nan
        nan]


### Expressing Conditional Logic as Array Operations

In [114]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [89]:
#zip 함수를 이용해 xarr,yarr,cond를 묶고, cond가 True이면 x,Flase이면 y값으로 이루어진 list를 comprehension을 이용해 출력하기
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [90]:
#where함수는 파라미터로 3개의 값을 갖는데, 첫번째 값에 Boolean값이 오고, 맞으면 두번째값, 틀리면 3번째값을 출력한다
#즉 바로 위 코드를 간단하게 표현한다고 볼 수 있다.
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [91]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2,  2],
       [-2,  2, -2, -2],
       [ 2, -2, -2,  2],
       [ 2, -2,  2, -2]])

In [92]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        ,  2.        , -0.679801  ,  2.        ],
       [-0.54622613,  2.        , -0.18069466, -0.10164749],
       [ 2.        , -0.72403838, -1.41682207,  2.        ],
       [ 2.        , -0.66344338,  2.        , -0.36140009]])

### Mathematical and Statistical Methods

In [115]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())
#array. 이후 mean,sum이오면 각각 모든원소의 평균,합 을 출력한다.

[[ 0.3087332  -0.67133876  1.41040812  1.09523273]
 [ 0.77182942  0.30008762  0.50774698  1.62847234]
 [ 1.08793309 -0.84805517 -0.86610736  1.16004202]
 [ 0.49694469 -0.03581642  1.67538558 -2.18419349]
 [ 1.71716783  0.10717754 -0.76897657  0.3005662 ]]
0.35966197975379754
0.35966197975379754
7.1932395950759505


In [116]:
print(arr.mean(axis=1))
print(arr.sum(axis=0))
#mean(axis=1)의 경우 행에 대한 평균을 출력하고
#sum(axis=0)의 경우 열에 대한 합을 출력한다.

[ 0.53575882  0.80203409  0.13345314 -0.01191991  0.33898375]
[ 4.38260823 -1.14794518  1.95845676  2.0001198 ]


In [95]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [96]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [122]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

(np.array([[3,4,2,3,5]])>2).sum()#np.array의 boolean값을 판단하여 True가 총 몇개인지 출력한다
#위 기능은 list 의 경우 지원해주지 않는다. 이상하다이상해~~

4

In [123]:
# .any함수는 하나라도 True이면 True가 출력되고, .all함수는 모두 True일때만 True가 출력된다,
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


### Sorting

In [99]:
arr = np.random.randn(6)
arr
arr.sort()
arr

array([-1.2427884 , -0.44137625, -0.10915251, -0.003575  ,  0.26877908,
        1.06710568])

In [124]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

array([[-3.24131018, -1.50844959,  0.35166859],
       [-0.11502166,  0.12139423,  0.48861439],
       [ 0.44745671,  0.96737468,  1.9359664 ],
       [-0.71538691,  0.92719854,  1.68718903],
       [-0.02932092,  0.5176829 ,  1.45904763]])

In [128]:
large_arr = np.random.randn(100)
print(large_arr) #무작위로 10개의 값을 출력
large_arr.sort()
print(large_arr) #위에 출력된 값들을 정렬시킨 array. default값은 오름차순
print(large_arr[int(0.05 * len(large_arr))])# 5% quantile
#마지막문법을 보면, 순서대로 정렬된 값들의 밑에서 5퍼센트의 값을 정수로 변환하여 index를 취하고 있다.
#이때 데이터가 총 100개라면, 하위 5퍼센트는 100*0.05인 5번째 index값일 것이다 따라서 정렬된 리스트중 5번째 index값의 원소가 출력된다

[ 1.08891115  0.45442743  1.19286241 -0.0790334  -1.29590113  0.23026187
 -0.30544632 -0.40802694  0.20626269 -0.42223218 -0.67221492  0.96771741
 -1.23423214  0.12390471  0.15273721 -0.27760638 -0.49698978  0.81100254
 -0.82422012  0.83407302 -1.77772466  1.21094743 -0.45509253 -0.21582953
 -1.51360255  1.71698519 -1.04057075  1.00648084 -0.97276745  0.16699026
  0.98262085  0.64628157  0.69444152 -0.34765388  0.03954807 -1.31720401
  1.6380037  -1.91157558  1.3029423  -0.34981297  0.93432103  0.93226306
 -0.23392275 -0.26019022  1.69232326 -0.44627028 -0.57749557 -0.26114525
 -1.285926    1.86656886  0.99075989 -0.56408164 -1.72405654  0.29297276
 -0.39010816 -0.98322242  0.6873921  -0.12356246  0.01695383 -0.16774979
  1.23222231  1.52767952 -0.40175493  0.05306919 -0.21362296 -1.64561955
 -0.53900046  0.82048955 -1.44118397 -1.66576265 -1.67508366 -0.65215153
 -1.18074427 -0.87541107 -0.5093626   0.6385733  -0.79356961 -0.5114811
  1.38851363 -0.47269293  0.16561644  1.09356584 -1.